Fix for arc angles being incorrect at high values
srwalter/garmin-tesla pull request #18
Opened 2021-08-05 20:20 UTC by paulobrien

This resolves an issue with the arc angles being incorrect at high values. Pesky maths! 😁

2021-09-07 13:42 UTC, hobbe requested changes

2021-09-07 13:42 UTC, hobbe commented on resources-fre/strings/strings.xml
> +    <string id="wake" scope="glance">Rréveiller </string>
```suggestion
    <string id="wake" scope="glance">Réveiller </string>
```

2021-09-07 13:42 UTC, hobbe commented on resources-fre/strings/strings.xml
> +    <string id="label_asleep" scope="background">Endormie</string>
```suggestion
    <string id="label_asleep" scope="background">En veille</string>
```

2021-09-07 13:42 UTC, hobbe commented on resources-fre/strings/strings.xml
> +    <string id="label_status_unknown" scope="glance">Statut inconnu</string>
```suggestion
    <string id="label_status_unknown" scope="glance">État inconnu</string>
```

2021-09-07 13:42 UTC, hobbe commented on resources-fre/strings/strings.xml
> +    <string id="label_on">Arrêter</string>
```suggestion
    <string id="label_off">Off</string>
    <string id="label_on">On</string>
```
I guess we could keep On/Off for this case and to keep text short.

2021-09-07 13:42 UTC, hobbe commented on resources-fre/strings/strings.xml
> +    <string id="label_no_vehicles">Pas de véhicules</string>
```suggestion
    <string id="label_no_vehicles">Pas de véhicule</string>
```

2021-09-07 14:04 UTC, paulobrien commented
Thank you for the translation fixes @hobbe 😃

2021-09-16 08:20 UTC, paulobrien commented
Currently in discussion with @srwalter re: how best to optimise support for non-touchscreen devices in the glance view

2021-09-28 18:32 UTC, srwalter commented
Any update on fixing support for non-touch devices?

2021-09-28 18:37 UTC, paulobrien commented
In progress @srwalter, hence set to WIP status for now.

2021-10-28 18:37 UTC, paulobrien commented
Finally done and ready I think! 😃

2021-10-30 19:52 UTC, merged